---

- name: Remove A records that points to the servers IP
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ awx_base_domain }}'
    record: '{{ item }}'
    type: A
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  with_items: "{{ awx_subdomain }}"
  ignore_errors: true
  register: record_ipv4

- name: Remove A record that points to the Load Balancer
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ awx_base_domain }}'
    record: "{{ rke2_load_balancer | regex_replace('(\\.)(.*)$', '') }}"
    type: A
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  when: ( rke2_api_ip | length > 0 )
  run_once: True
  ignore_errors: true

- name: Remove A record for Rancher
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ awx_base_domain }}'
    record: "rancher"
    type: A
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  when: ( rke2_api_ip | length > 0 )
  run_once: True
  ignore_errors: true

- name: Remove A record for AWX
  delegate_to: 127.0.0.1
  community.general.cloudflare_dns:
    zone: '{{ awx_base_domain }}'
    record: "awx"
    type: A
    account_email: '{{ cloudflare_email }}'
    account_api_token: '{{ cloudflare_api_token }}'
    state: absent
  when: ( rke2_api_ip | length > 0 )