---

- debug:
    msg: "ansible_play_hosts: {{ ansible_play_hosts }}"
  run_once: True

#- name: DEBUG print do_certificate variable
#  debug:
#    msg: "do_certificate: {{ do_certificate }}"
#  run_once: True
#  tags: [ 'never', 'provision' ]

- name: Create DigitalOcean Load Balancer #, add all Droplets with the 'rke2-master' tag
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_load_balancer:
    name: "leader.{{ awx_base_domain }}"
    state: present
    region: "{{ do_droplet_region }}"
    forwarding_rules:
      - entry_protocol: https
        entry_port: 9345
        target_protocol: https
        target_port: 9345
        tls_passthrough: true
    tag: rke2-master
    oauth_token: '{{ do_api_token }}'
  run_once: True
  tags: [ 'never', 'provision' ]

- name: Gather facts about all load balancers
  delegate_to: 127.0.0.1
  community.digitalocean.digital_ocean_load_balancer_info:
    oauth_token: "{{ do_api_token }}"
  register: load_balancer_facts
  run_once: True

- debug:
    msg: "load_balancer_facts: {{ load_balancer_facts }}"

#- name: Assign load balancer IPv4 to the rke2_api_ip variable
#  set_fact:
#    rke2_api_ip: "{{ load_balancer_facts.data | json_query(query) | first }}"
#  vars:
#    query: "[?name=='leader.{{ awx_base_domain }}'].ip"
#  run_once: True

- name: Collect public IPv4 address of RKE2 bootstrap node
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.shell: |
      ip addr show eth0 | grep -Po 'inet \K[\d.]+'
  register: rke2_bootstrap_node_ipv4

- name: HACK assign bootstrap nodes IP to the rke2_api_ip variable
  set_fact:
    rke2_api_ip: "{{ rke2_bootstrap_node_ipv4.stdout }}"
  run_once: True

- name: Add rke2_api_ip to group variables file
  delegate_to: 127.0.0.1
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all.yml"
    insertafter: "^# RKE2 Variables.*$"
    regexp: "^rke2_api_ip:"
    line: 'rke2_api_ip: "{{ rke2_api_ip }}"'
    state: present
  run_once: True