---

- name: Immediately shutdown the VM
  community.general.shutdown:
    delay: 0
  ignore_unreachable: true
  ignore_errors: true

- name: Stop the proxmox VMs
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ inventory_hostname }}"
    node: "{{ proxmox_node }}"
    force: true
    state: stopped
    timeout: 180
  when: proxmox_method == "clone"
  register: old_server_info
  ignore_errors: true

- name: Stop the proxmox LXC containers
  delegate_to: 127.0.0.1
  community.general.proxmox:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    hostname: "{{ inventory_hostname }}"
    vmid: "{{ vmid | int }}"
    node: "{{ proxmox_node }}"
    force: true
    state: stopped
    timeout: 180
  when: proxmox_method == "lxc"
  register: old_server_info
  ignore_errors: true

- debug:
    msg: "{{ old_server_info }}"

- name: Set string fact for VM stopped status
  set_fact:
    stopped_status: "status: stopped"

- name: DEBUG print vmid
  debug:
    msg: "vmid: {{ vmid }}"

- name: Check if target VM is stopped for up to 180 seconds
  delegate_to: "{{ proxmox_node }}"
  command: "sudo qm status {{ vmid }}"
  when: proxmox_method == "clone"
  register: vm_status
  until: vm_status.stdout == stopped_status
  retries: 12
  delay: 15

- name: Check if target LXC container is stopped for up to 180 seconds
  delegate_to: "{{ proxmox_node }}"
  command: "sudo pct status {{ vmid }}"
  when: proxmox_method == "lxc"
  register: ct_status
  until: stopped_status in ct_status.stdout
  retries: 12
  delay: 15

- name: Delete the proxmox VM
  delegate_to: 127.0.0.1
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ inventory_hostname }}"
    node: "{{ proxmox_node }}"
    force: true
    state: absent
    timeout: 180
  when: proxmox_method == "clone"
  register: old_server_info_2

- name: Delete the proxmox LXC containers
  delegate_to: 127.0.0.1
  community.general.proxmox:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    vmid: "{{ vmid }}"
    node: "{{ proxmox_node }}"
    state: absent
  when: proxmox_method == "lxc"
  register: delete_container_result
  ignore_errors: true

- debug:
    msg: "{{ old_server_info_2 }}"