---

- name: Create new disks for each agent node in Proxmox (do not rewrite in case it exists already)
  delegate_to: 127.0.0.1
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ inventory_hostname }}"
    disk: "virtio{{ item }}"
    backup: false
    cache: none
    storage: "{{ proxmox_storage }}"
    size: "{{ volume_size }}"
    state: present
  when: rke2_type == "agent"
  with_sequence: start=1 end={{ number_of_volumes }}
  register: new_volumes

#- name: DEBUG print new volumes
#  debug:
#    msg: "{{ new_volumes }}"