---

- name: Create a new AWX OAuth token using the admin username/password
  delegate_to: 127.0.0.1
  awx.awx.token:
    description: |
        AWX Primary Token "{{ lookup('pipe', 'date +%Y-%m-%d@$H:%M:%S') }}"
    scope: "write"
    state: present
    controller_host: "https://{{ awx_domain }}"
    controller_username: "{{ awx_admin_username }}"
    controller_password: "{{ awx_admin_password }}"
    validate_certs: "{{ validate_certs }}"
  register: awx_token
  #no_log: true
  run_once: true

#- name: debug
#  debug:
#    msg: "{{ awx_token.ansible_facts.tower_token.token }}"

- name: Define awx_oauth_token Ansible fact
  set_fact:
    awx_oauth_token: "{{ awx_token.ansible_facts.tower_token.token }}"
  no_log: true
  run_once: true
