---

- name: Remove the default 'Demo Job Template'
  delegate_to: 127.0.0.1
  awx.awx.job_template:
    name: "Demo Job Template"
    job_type: run
    project: "Demo Project"
    playbook: hello_world.yml
    state: absent
    controller_host: "https://{{ awx_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true

- name: Remove the default 'Demo Project'
  delegate_to: 127.0.0.1
  awx.awx.project:
    name: "Demo Project"
    organization: "Default"
    state: absent
    controller_host: "https://{{ awx_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: true
  run_once: true

- name: Remove the default 'Demo Inventory'
  delegate_to: 127.0.0.1
  awx.awx.inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    controller_host: "https://{{ awx_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: true
  run_once: true

- name: Remove the default 'Demo Credential' credential
  delegate_to: 127.0.0.1
  awx.awx.credential:
    name: "Demo Credential"
    user: "admin"
    credential_type: "Machine"
    state: absent
    controller_host: "https://{{ awx_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: true
  run_once: true

- name: Remove the default 'Default' organisation
  delegate_to: 127.0.0.1
  awx.awx.organization:
    name: "Default"
    state: absent
    controller_host: "https://{{ awx_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  ignore_errors: true
  run_once: true
