---

- name: Check if vault password-file exists
  delegate_to: 127.0.0.1
  ansible.builtin.stat:
    path: '{{ playbook_dir }}/vault/password-file'
  register: vault_password_file
  run_once: true

- name: Create Ansible Vault password file if it doesn't exist
  delegate_to: 127.0.0.1
  ansible.builtin.copy:
    content: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
    dest: "{{ playbook_dir }}/vault/password-file"
    mode: '0600'
  when: not vault_password_file.stat.exists
  no_log: true
  run_once: true
