---

#- name: Add machine credential
#  awx.awx.credential:
#    name: "AWX SSH Key"
#    description: "The SSH key for AWX to connect to its own host OS."
#    organization: "{{ awx_org_name }}"
#    credential_type: Machine
#    state: present
#    inputs:
#      ssh_key_unlock: "{{ awx_ssh_key_password }}"
#      ssh_key_data: "{{ lookup('file', '{{ awx_ssh_key }}') }}"
#    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
#    controller_oauthtoken: "{{ awx_oauth_token }}"
#    validate_certs: "{{ validate_certs }}"

- name: Read the awx_vault_password variabile from the ./vault/password-file file
  delegate_to: 127.0.0.1
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/vault/password-file"
  register: awx_vault_password_file_content
  run_once: true
  #no_log: true

- name: Set the awx_vault_password variable
  set_fact:
    awx_vault_password: "{{ awx_vault_password_file_content['content'] | b64decode }}"
  run_once: true
  no_log: true

- name: Create a Vault credential for AWX /group_vars/secret.yml file
  delegate_to: 127.0.0.1
  awx.awx.credential:
    name: "AWX Vault Secret"
    description: "An AWX vault secret that unlocks encrypted variables."
    organization: "{{ awx_org_name }}"
    credential_type: Vault
    state: present
    inputs:
      vault_id: "awx-secrets"
      vault_password: "{{ awx_vault_password }}"
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true 

- name: Read private key for AWX Resources repository
  delegate_to: 127.0.0.1
  ansible.builtin.slurp:
    src: "{{ awx_resources_deploy_key }}"
  register: awx_resources_deploy_key_content
  run_once: true

- name: Add a SCM credential for the AWX Resources repository
  delegate_to: 127.0.0.1
  awx.awx.credential:
    name: "AWX Resources SCM"
    description: "The SCM credential for the AWX Resources repository."
    organization: "{{ awx_org_name }}"
    credential_type: Source Control
    state: present
    inputs:
      username: "{{ awx_resources_git_username }}"
      ssh_key_data: "{{ awx_resources_deploy_key_content['content'] | b64decode }}"
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true