---

# Creates a vault password file if it doesn't exist at ./vault/password-file
- import_tasks: "{{ role_path }}/tasks/create_vault_password_file.yml"
  tags: [ 'never', 'ansible-vault' ]

# Decrypts the ./group_vars/secrets.yml variable file if it exists
- import_tasks: "{{ role_path }}/tasks/vault_decrypt.yml"
  tags: [ 'never', 'configure-awx', 'ansible-vault' ]

# Generates ./group_vars/secrets.yml if it doesn't exist and generates a OAuth token for AWX
- import_tasks: "{{ role_path }}/tasks/awx_token.yml"
  tags: [ 'never', 'awx-token' ]

# AWX cleanup default configuration
- import_tasks: "{{ role_path }}/tasks/cleanup_defaults.yml"
  tags: [ 'never', 'configure-awx' ]

# AWX configure organisations, user accounts and inventories
- import_tasks: "{{ role_path }}/tasks/users_org_inventory_awx.yml"
  tags: [ 'never', 'configure-awx' ]

# AWX configure credentials
- import_tasks: "{{ role_path }}/tasks/credentials_awx.yml"
  tags: [ 'never', 'configure-awx' ]

# AWX configure projects
- import_tasks: "{{ role_path }}/tasks/projects_awx.yml"
  tags: [ 'never', 'configure-awx' ]

# AWX configure job templates
- import_tasks: "{{ role_path }}/tasks/templates_awx.yml"
  tags: [ 'never', 'configure-awx' ]

# AWX configure job schedules
- import_tasks: "{{ role_path }}/tasks/schedules_awx.yml"
  tags: [ 'never', 'configure-awx' ]

# Encrypts the ./group_vars/secrets.yml variable file with any saved variables
- import_tasks: "{{ role_path }}/tasks/vault_encrypt.yml"
  tags: [ 'never', 'configure-awx', 'ansible-vault' ]