---

- name: Add 'AWX Ansible' project to AWX admins organisation
  delegate_to: 127.0.0.1
  awx.awx.project:
    name: "AWX Ansible"
    description: "An example playbook for this AWX setup."
    organization: "{{ org_name }}"
    scm_type: git
    scm_url: "{{ deploy_source }}"
    scm_branch: "{{ deploy_branch }}"
    scm_delete_on_update: yes
    scm_update_on_launch: no
    state: present
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true

- name: Update 'AWX Ansible' project
  delegate_to: 127.0.0.1
  awx.awx.project_update:
    name: "AWX Ansible"
    timeout: 300
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true