---

- name: Add 'AWX Ansible' project to AWX admins organisation
  delegate_to: 127.0.0.1
  awx.awx.project:
    name: "AWX Ansible"
    description: "The playbook for this AWX setup."
    organization: "{{ awx_org_name }}"
    scm_type: git
    scm_url: "{{ awx_deploy_source }}"
    scm_branch: "{{ awx_deploy_branch }}"
    scm_delete_on_update: yes
    scm_update_on_launch: no
    state: present
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true

- name: Update 'AWX Ansible' project
  delegate_to: 127.0.0.1
  awx.awx.project_update:
    name: "AWX Ansible"
    timeout: 300
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true

- name: Add 'AWX Resources' project to AWX admins organisation
  delegate_to: 127.0.0.1
  awx.awx.project:
    name: "AWX Resources"
    description: "The external playbook for resources being setup on this AWX instance."
    organization: "{{ awx_org_name }}"
    scm_type: git
    scm_url: "{{ awx_resources_source }}"
    scm_branch: "{{ awx_resources_branch }}"
    scm_delete_on_update: yes
    scm_update_on_launch: no
    credential: "AWX Resources SCM"
    state: present
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true

- name: Update 'AWX Resources' project
  delegate_to: 127.0.0.1
  awx.awx.project_update:
    name: "AWX Resources"
    timeout: 300
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_oauth_token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true