---

- name: Create 'AWX Status Check' job template
  delegate_to: 127.0.0.1
  awx.awx.job_template:
    name: "AWX Status Check"
    description: "Checks to see if the AWX server is functional."
    job_type: run
    inventory: "AWX Server"
    project: "AWX Ansible"
    playbook: "playbooks/check_awx.yml"
    #credentials: [ "AWX SSH Key", "Borgmatic Password" ]
    extra_vars: { awx_url: "{{ awx_subdomain }}.{{ awx_base_domain }}", awx_token: "{{ awx_session_token.ansible_facts.tower_token.token }}" }
    state: present
    verbosity: 1
    controller_host: "https://{{ awx_subdomain }}.{{ awx_base_domain }}"
    controller_oauthtoken: "{{ awx_session_token.ansible_facts.tower_token.token }}"
    validate_certs: "{{ validate_certs }}"
  run_once: true