---

- name: Set hostname for each RKE2 node to its domain
  hostname:
    name: "{{ rke2_subdomain }}.{{ awx_domain.split('.')[1:] | join('.') }}"

- name: Disable all swap on AWX/Rancher server
  ansible.builtin.command: swapoff -a

#- name: Comment out swap partition in /etc/fstab
#  ansible.builtin.lineinfile:
#    path: /etc/fstab
#    regexp: '^[^#].*swap.*$'
#    line: '# {{ line }}'

- name: Update repos
  ansible.builtin.package:
    update_cache: yes
  register: package_status
  until: package_status is success
  delay: 6
  retries: 10

- name: Upgrade all packages
  ansible.builtin.package:
    name: "*"
    state: latest
  register: package_status
  until: package_status is success
  delay: 6
  retries: 10

- name: Add prerequisite packages
  ansible.builtin.package:
    pkg:
    - ufw
    - apt-transport-https
    - gnupg2
    - apt-listchanges
    - git
    - etckeeper
    - prometheus
    - prometheus-node-exporter
  register: package_status
  until: package_status is success
  delay: 6
  retries: 10

- name: Make sure Prometheus unit is running and enabled on AWX Server
  ansible.builtin.systemd:
    state: started
    name: prometheus
    enabled: yes

- name: Make sure Prometheus Node Exporter unit is running and enabled on AWX Server
  ansible.builtin.systemd:
    state: started
    name: prometheus-node-exporter
    enabled: yes

- name: Ensure /etc/rke2/ directory exists on RKE2 server nodes
  file:
    path: /etc/rke2/
    state: directory
    mode: '0755'
  when: rke2_type == 'server'

- name: Ensure /etc/rancher/rke2 directory exists on all RKE2 nodes
  file:
    path: /etc/rancher/rke2
    recurse: yes
    state: directory
    mode: '0755'
