---

- name: Include vault secrets or handle decryption error
  block:

    - name: "If it does, include the variables in vault/secrets/ehi-bootstrap-playbook/{{ inventory_dir | basename }}/secrets.yml"
      delegate_to: localhost
      include_vars:
        file: "{{ playbook_dir }}/vault/secrets/ehi-bootstrap-playbook/{{ inventory_dir | basename }}/secrets.yml"
      no_log: True
      run_once: true
      when: secrets_file.stat.exists

  rescue:

    - name: Set failed_to_decrypt string
      delegate_to: localhost
      ansible.builtin.set_fact:
        failed_to_decrypt: "Attempting to decrypt but no vault secrets found"
      run_once: true

    - name: 'If the decryption of secrets.yml fails, exit the playbook, then prompt the user to use the vault file'
      debug:
        msg:
        - "Please run the playbook again with the vault password file, for example:"
        - "$ ansible-playbook -i inventories/dev/ setup.yml --vault-password-file vault/password-file"
        - "" 
        - "Alternatively, you can set the ANSIBLE_VAULT_PASSWORD_FILE environment variable to the path of the vault password file first. For example:"
        - "$ export MY_VAULT_PASSWORD_FILE=/path/to/playbook/vault/password-file"
        - "$ ansible-playbook -i inventories/dev/ setup.yml"
      when: failed_to_decrypt in ansible_failed_result.message
      run_once: true

    - name: 'Exiting the playbook'
      delegate_to: localhost
      ansible.builtin.fail:
      when: failed_to_decrypt in ansible_failed_result.message
      run_once: true
