---

- name: Ensure /root/awx-operator directory exists
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.file:
    path: /root/awx-operator
    state: directory
    mode: 0755
  run_once: True

# Install Kustomize!

# wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_amd64.tar.gz

- name: Download Kustomize binary
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.get_url: 
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_amd64.tar.gz
    dest: /root/awx-operator/kustomize.tar.gz

- name: Extract Kustomize binary
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.unarchive:
    src: /root/awx-operator/kustomize.tar.gz
    dest: /var/lib/rancher/rke2/bin
    remote_src: yes
    owner: root
    group: root
    mode: 755
  run_once: True

#    Apply the manifest with kustomize build . | kubectl apply -f -
#    After a bit of waiting, you should see some AWX Operator pods happily running.

- name: Template the kustomize manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/kustomization.yaml.j2"
    dest: /root/awx-operator/kustomization.yaml
    mode: 0644
  run_once: True

- name: Apply the kustomize manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.shell: |
    kustomize build /root/awx-operator | kubectl apply -f -
  run_once: True

#wings:homelab-dns/ $ kubectl get pods -n awx
#NAME                                               READY   STATUS    RESTARTS        AGE
#awx-operator-controller-manager-57d56b64db-kfcjf   2/2     Running   0               3m

#You've just installed AWX Operator. Crack open a beer or put on a coffee, you've earned it.

- name: Examine the AWX pods
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl get pods -n awx
  run_once: True

# root@awx1:~# kubectl get pods -n awx --kubeconfig=/etc/rancher/rke2/rke2.yaml
# NAME                                               READY   STATUS    RESTARTS   AGE
# awx-operator-controller-manager-7b79cf89db-kxt26   2/2     Running   0          15m


# And apply it with kubectl apply -f awx.yaml.

- name: Template the AWX Operator manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/operator.yaml.j2"
    dest: /root/awx-operator/operator.yaml
    mode: 0644
  run_once: True

- name: Apply the AWX Operator manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/awx-operator/operator.yaml
  run_once: True

- name: Check if AWX/Automation Controller is deployed (max 3min)
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl -n awx logs --tail=10 deployments/awx-operator-controller-manager -c awx-manager
  register: result
  until: result.stdout.find("failed=0") != -1
  failed_when: result.stdout.find("failed=1") != -1
  run_once: True
  retries: 5
  delay: 30

- name: Deploy the required AWX/Automation Controller Operator objects in the awx namespace.
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl -n awx get awx,all,ingress,secrets
  run_once: True

- name: Ensure /root/awx/ directory exists on bootstrap node
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.file:
    path: /root/awx
    state: directory
    mode: 0755
  run_once: True

#Save this as awx.perthchat2.org-admin-secret.yml
#
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: awx-perthchat2-admin-secret
#  namespace: awx
#stringData:
#  password: {{ awx_admin_password }}
#
#Apply with kubectl apply -f awx.perthchat2.org-admin-secret.yml

- name: Template the admin secret
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/admin-secret.yaml.j2"
    dest: /root/awx/{{ awx_subdomain }}.{{ awx_base_domain }}-admin-secret.yaml
    mode: 0644
  run_once: True

- name: Apply the admin secret
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/awx/{{ awx_subdomain }}.{{ awx_base_domain }}-admin-secret.yaml
  run_once: True

#root@awx1:~# cat ./awxes/awx.perthchat2.org.yaml 

- name: Template the AWX manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/awx.yaml.j2"
    dest: /root/awx/{{ awx_subdomain }}.{{ awx_base_domain }}.yaml
    mode: 0644
  run_once: True

# kubectl apply -f awx.perthchat2.org.yaml

- name: Apply the AWX manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/awx/{{ awx_subdomain }}.{{ awx_base_domain }}.yaml
  run_once: True