---

- name: Create /root/cert-manager directory
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.file:
    path: /root/cert-manager
    state: directory
    mode: 0755
  run_once: True

- name: Template the issuer.yaml for Cert-Manager
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/issuer.yaml.j2"
    dest: /root/cert-manager/issuer.yaml
    mode: 0644
  run_once: True

# kubectl apply -f issuer.yaml.

- name: Deploy the Cert-Manager issuer
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/cert-manager/issuer.yaml
  run_once: True

# kubectl apply -f cloudflare.yaml --namespace=cert-manager.

- name: Template the cloudflare.yaml for Cert-Manager
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/cloudflare.yaml.j2"
    dest: /root/cert-manager/cloudflare.yaml
    mode: 0644
  run_once: True

- name: Deploy the Cloudflare manifest
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/cert-manager/cloudflare.yaml --namespace=cert-manager
  run_once: True

# Once you've got your manifest created, apply it with kubectl apply -f certificate.yaml

- name: Template the certificate.yaml for Cert-Manager
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.template:
    src: "{{ role_path }}/templates/certificate.yaml.j2"
    dest: /root/cert-manager/certificate.yaml
    mode: 0644
  run_once: True

- name: Create 'awx' namespace for AWX
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl create namespace awx
  run_once: True
  ignore_errors: True

- name: Deploy the Cert-Manager certificate
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl apply -f /root/cert-manager/certificate.yaml
  run_once: True

# You can run kubectl get certificates to see your certificate request, and kubectl describe certificates to see what state it's in.

# wings:homelab-dns/ $ kubectl get certificates

- name: Verify that the Cert-Manager certificate is ready
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl get certificates --namespace=awx
  register: certificate_state
  run_once: True
  retries: 6
  delay: 10
  until: "'True' in certificate_state.stdout"
  ignore_errors: True

# need to keep going until this output is here:

# root@awx1:~# kubectl get certificates --namespace=awx --kubeconfig=/etc/rancher/rke2/rke2.yaml
# NAME              READY   SECRET            AGE
# tls-awx-ingress   True    tls-awx-ingress   10m

- name: DEBUG print certificate_state
  ansible.builtin.debug:
    msg: "{{ certificate_state.stdout_lines }}"
  run_once: True

# kubectl describe challenges

- name: Examine the state of the Cert-Manager challenges
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.command: |
    kubectl describe challenges --namespace=awx
  register: challenge_state
  run_once: True

- name: DEBUG print challenge_state
  ansible.builtin.debug:
    msg: "{{ challenge_state.stdout_lines }}"
  run_once: True