---

# Create TLS secrets for AWX
- import_tasks: "{{ role_path }}/tasks/awx_tls_setup.yml"
  tags: [ 'never', 'awx-setup' ]

# Deploy AWX to K3s/Kubernetes
- import_tasks: "{{ role_path }}/tasks/awx_setup.yml"
  tags: [ 'never', 'awx-setup' ]
