---

# Print the RKE2 version

- name: Print the RKE2 version
  debug:
    msg: "RKE2 version: {{ rke2_version }}"
  tags: [ 'never', 'rke2-setup' ]

# Print the RKE2 server version

- name: Print the RKE2 server version
  debug:
    msg: "RKE2 server version: {{ rke2_server_version }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Print the RKE2 agent version

- name: Print the RKE2 agent version
  debug:
    msg: "RKE2 agent version: {{ rke2_agent_version }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Print the RKE2 server image

- name: Print the RKE2 server image
  debug:
    msg: "RKE2 server image: {{ rke2_server_image }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Print the RKE2 agent image

- name: Print the RKE2 agent image
  debug:
    msg: "RKE2 agent image: {{ rke2_agent_image }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Print rke2_api_ip variable

- name: Print rke2_api_ip variable
  debug:
    msg: "rke2_api_ip: {{ rke2_api_ip }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Print rke2_token variable

- name: Print rke2_api_ip variable
  debug:
    msg: "rke2_token: {{ rke2_token }}"
  ignore_errors: True
  tags: [ 'never', 'rke2-setup' ]

# Worker nodes aren't being labelled strangely...

- name: Label the additional nodes as worker
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl label node {{ awx_subdomain }}.{{ awx_base_domain }} node-role.kubernetes.io/worker=worker --overwrite
  environment:
    KUBECONFIG: "/etc/rancher/rke2/rke2.yaml"
  when: rke2_type == 'agent'
  tags: [ 'never', 'rke2-setup' ]

# ^ Why aren't these being labelled by the role?

- name: Confirm cluster is functional
  delegate_to: "{{ rke2_bootstrap_node }}"
  ansible.builtin.shell: |
      /var/lib/rancher/rke2/bin/kubectl get nodes --kubeconfig /etc/rancher/rke2/rke2.yaml
  register: cluster_status
  run_once: True
  tags: [ 'never', 'rke2-setup' ]

- name: Display cluster status output
  ansible.builtin.debug:
    msg: "{{ cluster_status.stdout_lines }}"
  run_once: True
  tags: [ 'never', 'rke2-setup' ]
