
# RKE2 Settings
rke2_subdomain: dev-ebi-k8s-m02
rke2_type: server
rke2_download_kubeconf: true
#rke2_server_node_taints:
#  - 'CriticalAddonsOnly=true:NoExecute'

# Proxmox Settings
proxmox_host: "10.1.3.205"
proxmox_node: "eevee"
proxmox_template: "ubuntu22-template-64g-1"
proxmox_storage: "Crucial_SSD"

# Extra variables